@baseUrl = http://localhost:5001
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "wanny",
  "password": "qwerty",
  "email": "waniel@gmail.com",
  "avatarColor": "red",
  "avatarImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "lanny",
  "password": "lanny"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "laniel@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/d465278d16c4ea290fcc27694de4bb113789696b
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "lanny",
  "confirmPassword": "lanny"
}
