@baseUrl = http://localhost:5001
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/63c7ffaf021616d432abdc80
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/63c7ffaf021616d432abdc80
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/63c7ffaf021616d432abdc80/63c94c2a40ac6d03a3926482
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63ca600ad6d49233bd2949a1",
  "postId": "63ca6c1be2f2fd07adfa758a",
  "comment": "my comment 2",
  "profilePicture": "image"
}
