@baseUrl = http://localhost:5001
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/63c7ffaf021616d432abdc80
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/63c7ffaf021616d432abdc80
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/63c7ffaf021616d432abdc80/63c94c2a40ac6d03a3926482
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63c69252da53a3e85c8efbd5",
  "postId": "63c7ffaf021616d432abdc80",
  "comment": "my comment 2",
  "profilePicture": "image"
}
