@baseUrl = http://localhost:5001
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/63ca600ad6d49233bd2949a1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/63ca6092d6d49233bd2949ad
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/63ca6092d6d49233bd2949ad/63ca600ad6d49233bd2949a1
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/block/63ca6092d6d49233bd2949ad
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/63ca6092d6d49233bd2949ad
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
