@baseUrl = http://localhost:5001
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/all/1
# GET {{baseUrl}}/{{urlPath}}/post/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/images/1
# GET {{baseUrl}}/{{urlPath}}/post/images/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

# Privacy - Public | Private | Followers
# Feelings - like | love | wow | happy | sad | angry

{
  "post": "POST 3",
  "bgColor": "black",
  "privacy": "Private",
  "gifUrl": "",
  "profilePicture": "url",
  "feelings": "happy"
}

###
POST {{baseUrl}}/{{urlPath}}/post/image/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "profilePicture": "",
  "feelings": "",
  "image": "base64"
}

###
PUT {{baseUrl}}/{{urlPath}}/post/63c7fec8021616d432abdc7c
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "another post",
  "bgColor": "white",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "image",
  "feelings": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/post/image/63c7fec8021616d432abdc7c
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "profilePicture": "<cloudinary-user-profile-picture-url>",
  "feelings": "",
  "imgId": "<imgId-form-post>",
  "imgVersion": "<imgVersion-for-post>",
  "image": "<base64-encoded-string>"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/63c7fec8021616d432abdc7c
Content-Type: application/json
Accept: application/json
withCredentials: true
